In [1]:
source("/rd1/user/lit/project/sORFs/sORFs.utils.R")
source("~/bin/lit_utils.R")
lib_text()
lib_plot()
setwd("/rd1/user/lit/project/sORFs/analysis/20250523_human_ms_run")

Warning message:
“程辑包‘stringr’是用R版本4.3.2 来建造的”

In [2]:
output_path <- "stat_output/S4"
create_path(output_path)

In [3]:
read_file("./output/db_search_20250326/Trypsin/CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T_T_Slot1_46_1_4747_d/protein.tsv") -> protein
read_psm("./output/db_search_20250326/Trypsin/CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T_T_Slot1_46_1_4747_d/psm.tsv") -> psm

In [4]:
read.table("/rd1/user/lit/project/sORFs/analysis/20250404_tmp_from_nanjing/uniprot.human.sep.id.txt") -> uniprot.human.sep.id

In [5]:
system("grep -f /rd1/user/lit/project/sORFs/analysis/20250404_tmp_from_nanjing/uniprot.human.sep.id.txt /rd1/user/lit/project/sORFs/analysis/20250523_human_ms_run/output/db_search_20250326/Trypsin/CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T_T_Slot1_46_1_4747_d/psm.tsv > /rd1/user/lit/project/sORFs/analysis/20250523_human_ms_run/stat_output/S4/test_psm_contain_cano_sep.txt")

In [8]:
fread_c("stat_output/S4/test_psm_contain_cano_sep.txt") -> test_psm_contain_cano_sep
test_psm_contain_cano_sep -> df

In [9]:
colnames(psm)
colnames(df)

 [1] "Spectrum"                    "Spectrum.File"
 [3] "Peptide"                     "Modified.Peptide"
 [5] "Extended.Peptide"            "Prev.AA"
 [7] "Next.AA"                     "Peptide.Length"
 [9] "Charge"                      "Retention"
[11] "Observed.Mass"               "Calibrated.Observed.Mass"
[13] "Observed.M.Z"                "Calibrated.Observed.M.Z"
[15] "Calculated.Peptide.Mass"     "Calculated.M.Z"
[17] "Delta.Mass"                  "SpectralSim"
[19] "RTScore"                     "Expectation"
[21] "Hyperscore"                  "Nextscore"
[23] "Probability"                 "Number.of.Enzymatic.Termini"
[25] "Number.of.Missed.Cleavages"  "Protein.Start"
[27] "Protein.End"                 "Intensity"
[29] "Assigned.Modifications"      "Observed.Modifications"
[31] "Class"                       "Ion.Mobility"
[33] "Purity"                      "Is.Unique"
[35] "Protein"                     "Protein.ID"
[37] "Entry.Name"                  "Gene"
[39] "Protein.Description"         "Mapped.Genes"
[41] "Mapped.Proteins"             "Sample"

 [1] "V1"  "V2"  "V3"  "V4"  "V5"  "V6"  "V7"  "V8"  "V9"  "V10" "V11" "V12"
[13] "V13" "V14" "V15" "V16" "V17" "V18" "V19" "V20" "V21" "V22" "V23" "V24"
[25] "V25" "V26" "V27" "V28" "V29" "V30" "V31" "V32" "V33" "V34" "V35" "V36"
[37] "V37" "V38" "V39" "V40" "V41"

In [10]:
# head(df)
colnames(df) <- colnames(psm)[1:41]
head(df)

  Spectrum
1 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00640.00640.4
2 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00655.00655.2
3 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00663.00663.3
4 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00680.00680.4
5 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00682.00682.3
6 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00699.00699.4
  Spectrum.File
1 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
2 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
3 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
4 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
5 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
6 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
  Peptide       Modified.Peptide   Extended.Peptide               Prev.AA
1 RAPPTGGIKKPHR n[43]RAPPTGGIKKPHR .RAPPTGGIKKPHR.YKPGTIAI        -
2 LAHYNKR                          RIAGEASR.LAHYNKR.STITSRRS      R
3 HHEEEIVHHKK                      EQIAAIKK.HHEEEIVHHKK.EIERIQKE  K
4 RAPPTGGIKKPHR n[43]RAPPTGGIKKPHR .RAPPTGGIKKPHR.YKPGTIAI        -
5 KHHEEEIVHHKK                     REQIAAIK.KHHEEEIVHHKK.EIERIQKE K
6 RAPPTGGIKKPHR n[43]RAPPTGGIKKPHR .RAPPTGGIKKPHR.YKPGTIAI        -
  Next.AA Peptide.Length Charge Retention ⋯ Ion.Mobility Purity Is.Unique
1 Y       13             4      351.5718  ⋯ 0.7327       0      FALSE
2 S        7             2      353.9127  ⋯ 0.8132       0      FALSE
3 E       11             3      353.9127  ⋯ 0.7770       0      FALSE
4 Y       13             4      355.0846  ⋯ 0.7614       0      FALSE
5 E       12             3      355.0846  ⋯ 0.7997       0      FALSE
6 Y       13             4      356.2535  ⋯ 0.7645       0      FALSE
  Protein
1 ENST00000598383.3-chr5:17655127-17655454
2 ENST00000369385.5+chr1:149843083-149843533
3 ENST00000335514.10+chr1:28236189-28237978
4 ENST00000598383.3-chr5:17655127-17655454
5 ENST00000335514.10+chr1:28236189-28237978
6 ENST00000598383.3-chr5:17655127-17655454
  Protein.ID
1 ENST00000598383.3-chr5:17655127-17655454 PE=4
2 ENST00000369385.5+chr1:149843083-149843533 PE=4
3 ENST00000335514.10+chr1:28236189-28237978 PE=4
4 ENST00000598383.3-chr5:17655127-17655454 PE=4
5 ENST00000335514.10+chr1:28236189-28237978 PE=4
6 ENST00000598383.3-chr5:17655127-17655454 PE=4
  Entry.Name                                      Gene
1 ENST00000598383.3-chr5:17655127-17655454 PE=4
2 ENST00000369385.5+chr1:149843083-149843533 PE=4
3 ENST00000335514.10+chr1:28236189-28237978 PE=4
4 ENST00000598383.3-chr5:17655127-17655454 PE=4
5 ENST00000335514.10+chr1:28236189-28237978 PE=4
6 ENST00000598383.3-chr5:17655127-17655454 PE=4
  Protein.Description
1 ENST00000598383.3-chr5:17655127-17655454 PE=4
2 ENST00000369385.5+chr1:149843083-149843533 PE=4
3 ENST00000335514.10+chr1:28236189-28237978 PE=4
4 ENST00000598383.3-chr5:17655127-17655454 PE=4
5 ENST00000335514.10+chr1:28236189-28237978 PE=4
6 ENST00000598383.3-chr5:17655127-17655454 PE=4
  Mapped.Genes
1 H3Y1
2 H2BC11, H2BC12, H2BC13, H2BC14, H2BC15, H2BC17, H2BC18, H2BC19P, H2BC20P, H2BC21, H2BC26, H2BC3, H2BC4, H2BC5, H2BC9
3 ATP5IF1
4 H3Y1
5 ATP5IF1
6 H3Y1
  Mapped.Proteins
1 ENST00000598383.3-chr5:17655127-17655478, ENST00000598383.3-chr5:17655127-17655484, ENST00000598383.3-chr5:17655127-17655487, ENST00000598383.3-chr5:17655127-17655526, ENST00000598383.3-chr5:17655127-17655550, ENST00000598383.3-chr5:17655127-17655556, ENST00000598383.3-chr5:17655127-17655568, ENST00000598383.3-chr5:17655127-17655580, sp|P0DPK2|H3Y1_HUMAN

In [11]:
# 分组并且展开
df$Group_id <- 1:nrow(df)
df %>% separate_rows(`Mapped.Proteins`, convert = TRUE,sep=", ") -> tmp
tmp %>% mutate(Protein=`Mapped.Proteins`,
               `Protein.ID`=`Mapped.Proteins`,
               Gene=`Mapped.Proteins`,
               `Entry.Name`=`Mapped.Proteins`,
               `Protein.Description`=`Mapped.Proteins`) -> tmp_1
rbind(df,tmp_1) -> df_unfold

In [12]:
nrow(df)
nrow(df_unfold)
n_distinct(df$Group_id)

[1] 9069

[1] 506420

[1] 9069

In [13]:
# 先把组别中有非小肽的注释蛋白的去掉
df_unfold %>% filter(grepl("^sp",Protein)) %>% filter(!Protein %in% uniprot.human.sep.id$V1) -> df_anno_pro
unique(df_anno_pro$Group_id) -> df_anno_pro_gi

In [14]:
# 特异性+非特异性总共有多少经典的SEP
df_unfold %>% filter(Protein %in% uniprot.human.sep.id$V1) -> df_unfold_target
n_distinct(df_unfold_target$Protein)

[1] 1012

In [15]:
# 特异性+非特异性分别是哪些
df_unfold_target %>% group_by(Group_id) %>% filter(n()==1 & !Group_id %in% df_anno_pro_gi) -> df_unique
unique(df_unique$Group_id) -> df_unique_gi
df_unfold_target %>% group_by(Group_id) %>% filter(n()>1 | Group_id %in% df_anno_pro_gi) -> df_multiple
unique(df_multiple$Group_id) -> df_multiple_gi

In [16]:
# 合并结果
df_unfold_target %>% mutate(PSM_type=case_when(
    Group_id %in% df_unique_gi ~ "Unique",
    Group_id %in% df_multiple_gi ~ "NonUnique",
)) -> df_unfold_target_add_PSM_type

In [17]:
n_distinct(df_unfold_target_add_PSM_type$Protein)
df_unfold_target_add_PSM_type %>% group_by(PSM_type) %>% summarise(n_distincs=n_distinct(Protein))

[1] 1012

  PSM_type  n_distincs
1 NonUnique 704
2 Unique    401

In [18]:
fwrite(df_unfold_target_add_PSM_type,o("test_psm_cano_sep_all.txt"),sep='\t')

In [19]:
colnames(df_unfold_target_add_PSM_type)[c(1:41,43)]

 [1] "Spectrum"                    "Spectrum.File"
 [3] "Peptide"                     "Modified.Peptide"
 [5] "Extended.Peptide"            "Prev.AA"
 [7] "Next.AA"                     "Peptide.Length"
 [9] "Charge"                      "Retention"
[11] "Observed.Mass"               "Calibrated.Observed.Mass"
[13] "Observed.M.Z"                "Calibrated.Observed.M.Z"
[15] "Calculated.Peptide.Mass"     "Calculated.M.Z"
[17] "Delta.Mass"                  "SpectralSim"
[19] "RTScore"                     "Expectation"
[21] "Hyperscore"                  "Nextscore"
[23] "Probability"                 "Number.of.Enzymatic.Termini"
[25] "Number.of.Missed.Cleavages"  "Protein.Start"
[27] "Protein.End"                 "Intensity"
[29] "Assigned.Modifications"      "Observed.Modifications"
[31] "Class"                       "Ion.Mobility"
[33] "Purity"                      "Is.Unique"
[35] "Protein"                     "Protein.ID"
[37] "Entry.Name"                  "Gene"
[39] "Protein.Description"         "Mapped.Genes"
[41] "Mapped.Proteins"             "PSM_type"