In [1]:
source("/home/user/data2/lit/bin/lit_utils.R")
source("/home/user/data3/lit/project/sORFs/sORFs.utils.R")
lib_text()
lib_plot()

In [2]:
fread_c("/home/user/data3/lit/project/sORFs/01-ribo-seq/analysis/20251022_custom_fa_gtf/processed/orfs/PRICE/Human_brain.orfs.tsv") -> orfs

In [4]:
head(orfs)
nrow(orfs)

  Gene      Id                 Location               Candidate Location
1 WARS2-IT1 PB.2462.1_ncRNA_1  1+:119047264-119047276 1+:119047264-119047276
2 WARS2-IT1 PB.2462.1_ncRNA_0  1+:119047334-119047367 1+:119047319-119047367
3 WARS2-IT1 PB.2462.1_ncRNA_2  1+:119047477-119047486 1+:119047477-119047486
4 PAPPA2    PB.3326.2_ncRNA_0  1+:176555485-176555536 1+:176555485-176555536
5 LINC00623 PB.2508.71_ncRNA_1 1+:120942451-120942526 1+:120942451-120942526
6 LINC00623 PB.2508.71_ncRNA_2 1+:120952453-120952498 1+:120952453-120952498
  Codon Type  Start Range p value
1 ATG   ncRNA 0.42  0.27  0.7558600
2 ATA   ncRNA 0.12  0.20  0.0088559
3 ATG   ncRNA 0.47  0.24  0.4375000
4 AAG   ncRNA 0.42  0.25  0.1162100
5 AAG   ncRNA 0.13  0.25  0.3567300
6 ACG   ncRNA 0.47  0.29  0.7388100
  /home/user/data3/lit/project/sORFs/01-ribo-seq/analysis/20251022_custom_fa_gtf/processed/merged_bam/
1 11.0
2 20.0
3  6.6
4 14.1
5 44.5
6 32.5
  Total
1 11.0
2 20.0
3  6.6
4 14.1
5 44.5
6 32.5

[1] 193397

In [10]:
orfs %>% filter(`p value`<=0.05) %>% nrow()
orfs %>% filter(`p value`<=0.05 & Codon=="ATG" & Type!="CDS") %>% nrow()

[1] 29197

[1] 5622

In [7]:
adjusted_p <- p.adjust(orfs$`p value`, method = "BH")

In [12]:
sum(adjusted_p<=0.05)
orfs$adjusted_P <- adjusted_p

[1] 18334

In [48]:
head(orfs)
table(orfs$Type)

  Gene      Id                 Location               Candidate Location
1 WARS2-IT1 PB.2462.1_ncRNA_1  1+:119047264-119047276 1+:119047264-119047276
2 WARS2-IT1 PB.2462.1_ncRNA_0  1+:119047334-119047367 1+:119047319-119047367
3 WARS2-IT1 PB.2462.1_ncRNA_2  1+:119047477-119047486 1+:119047477-119047486
4 PAPPA2    PB.3326.2_ncRNA_0  1+:176555485-176555536 1+:176555485-176555536
5 LINC00623 PB.2508.71_ncRNA_1 1+:120942451-120942526 1+:120942451-120942526
6 LINC00623 PB.2508.71_ncRNA_2 1+:120952453-120952498 1+:120952453-120952498
  Codon Type  Start Range p value
1 ATG   ncRNA 0.42  0.27  0.7558600
2 ATA   ncRNA 0.12  0.20  0.0088559
3 ATG   ncRNA 0.47  0.24  0.4375000
4 AAG   ncRNA 0.42  0.25  0.1162100
5 AAG   ncRNA 0.13  0.25  0.3567300
6 ACG   ncRNA 0.47  0.29  0.7388100
  /home/user/data3/lit/project/sORFs/01-ribo-seq/analysis/20251022_custom_fa_gtf/processed/merged_bam/
1 11.0
2 20.0
3  6.6
4 14.1
5 44.5
6 32.5
  Total adjusted_P
1 11.0  1.00000000
2 20.0  0.08511698
3  6.6  1.00000000
4 14.1  0.56824519
5 44.5  0.94337227
6 32.5  1.00000000

    CDS    dORF    iORF   ncRNA  orphan   Trunc   uoORF    uORF Variant
   2465   28947   23929   98144    2025    8474    5755   20547    3111

In [33]:
# orfs %>% filter(adjusted_P<=0.05) %>% count(Type)
orfs %>% filter(adjusted_P<=0.05) %>% 
filter(Codon %in% c("ATG","TTG","CTG","GTG","ACG")) %>% 
filter(Type!="Trunc" & Type!="Variant") %>% count(Type) -> tmp
tmp
tmp %>% summarise(sum(n))

  Type   n
1 CDS    1392
2 dORF    561
3 iORF    184
4 ncRNA  3598
5 orphan   13
6 uORF   1717
7 uoORF   675

  sum(n)
1 8140

In [52]:
orfs %>% filter(adjusted_P<=0.05) %>% 
filter(Codon %in% c("ATG","TTG","CTG","GTG","ACG")) %>% 
filter(Type!="Trunc" & Type!="Variant") %>% count(Codon) %>% mutate(n/sum(n))

  Codon n    n/sum(n)
1 ACG    580 0.07125307
2 ATG   3754 0.46117936
3 CTG   1857 0.22813268
4 GTG   1205 0.14803440
5 TTG    744 0.09140049

In [30]:
fread_c("/home/user/data3/lit/project/sORFs/01-ribo-seq/analysis/20251022_custom_fa_gtf/processed/orfs/RiboCode/Human_brain_collapsed.txt") -> ribocode_orfs
head(ribocode_orfs,1) %>% print()

                     ORF_ID ORF_type alt_ORF_type transcript_id transcript_type
1 A1BG_58347580_58347503_25    novel            -    PB.22711.2            None
  gene_id gene_name gene_type chrom start_codon strand ORF_length ORF_tstart
1    A1BG      A1BG      None chr19         ATG      -         75         43
  ORF_tstop ORF_gstart ORF_gstop annotated_tstart annotated_tstop
1       120   58347580  58347503             None            None
  annotated_gstart annotated_gstop Psites_sum_frame0 Psites_sum_frame1
1             None            None                73                12
  Psites_sum_frame2 Psites_coverage_frame0 Psites_coverage_frame1
1                11                 24.00%                 12.00%
  Psites_coverage_frame2 Psites_frame0_RPKM pval_frame0_vs_frame1
1                 12.00%           4.712767            0.02427537
  pval_frame0_vs_frame2 pval_combined adjusted_pval                     AAseq
1            0.05352897   0.005633231    0.01832241 MPSCAARDPSPTSPSSCCARARRRP

In [55]:
count(ribocode_orfs,ORF_type)
count(ribocode_orfs,start_codon )

  ORF_type     n
1 Overlap_dORF  3250
2 Overlap_uORF  6810
3 annotated    20930
4 dORF         19027
5 internal     24554
6 novel        86672
7 uORF         18708

   start_codon n
1  ACG           8425
2  ACg              7
3  ATG         111238
4  ATg            213
5  Acg              6
6  Atg             74
7  CTG          27146
8  CTg             30
9  Ctg             12
10 GTG          10948
11 GTg              9
12 Gtg              7
13 TTG          14742
14 TTg              5
15 Ttg             12
16 aCG              9
17 aTG             65
18 aTg              1
19 acG              7
20 acg            321
21 atG             45
22 atg           3962
23 cTG             42
24 ctG             13
25 ctg           1327
26 gTG              9
27 gtg            543
28 tTG              6
29 ttG             11
30 ttg            716