In [25]:
source("~/bin/lit_utils.R")
lib_text()

In [1]:
f <- "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_F1_Slot2-51_1_3561_uncalibrated.mzML"

In [2]:
library("Spectra")
ms <- Spectra(f)

载入需要的程辑包：S4Vectors

载入需要的程辑包：stats4

载入需要的程辑包：BiocGenerics


载入程辑包：‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min



载入程辑包：‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


载入需要的程辑包：BiocParallel

载入需要的程辑包：ProtGenerics


载入程辑包：‘ProtGenerics’


The following object is masked from ‘package:stats’:

    smooth

In [4]:
ms2_count <- sum(msLevel(ms) == 2)
ms2_count

[1] 38051

In [29]:
mzml <- list.files("/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata", pattern = "*uncalibrated.mzML", full.names = TRUE,recursive = T)

In [30]:
length(mzml)

[1] 24

In [23]:
mzml

 [1] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_F1_Slot2-51_1_3561_uncalibrated.mzML"
 [2] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_F2_Slot2-52_1_3562_uncalibrated.mzML"
 [3] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_F3_Slot2-53_1_3563_uncalibrated.mzML"
 [4] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_F4_Slot2-54_1_3564_uncalibrated.mzML"
 [5] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_P1_Slot1-40_1_3551_uncalibrated.mzML"
 [6] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_P2_Slot1-41_1_3552_uncalibrated.mzML"
 [7] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_P3_Slot1-42_1_3553_uncalibrated.mzML"
 [8] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_P4_Slot1-43_1_3554_uncalibrated.mzML"
 [9] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_S1_Slot1-44_1_3556_uncalibrated.mzML"
[10] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_S2_Slot1-45_1_3557_uncalibrated.mzML"
[11] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_S3_Slot1-53_1_3558_uncalibrated.mzML"
[12] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241022licq_BSEP_PreExp_DDA_60min/CAD20241022licq_BSEP_PreExp_DDA_60min_S4_Slot1-54_1_3559_uncalibrated.mzML"
[13] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_E16-N_Slot2-6_1_3832_uncalibrated.mzML"
[14] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_E16-N-T1_Slot2-1_1_3826_uncalibrated.mzML"
[15] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_E16-N-T2_Slot2-2_1_3827_uncalibrated.mzML"
[16] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_E16-T_Slot2-7_1_3834_uncalibrated.mzML"
[17] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_E16-T-LT_Slot2-4_1_3830_uncalibrated.mzML"
[18] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_E16-T-T_Slot2-5_1_3831_uncalibrated.mzML"
[19] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_E16-T-TC_Slot2-3_1_3828_uncalibrated.mzML"
[20] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_m14-10_30K_Slot2-45_1_3837_uncalibrated.mzML"
[21] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_m14-3_10K_Slot2-9_1_3836_uncalibrated.mzML"
[22] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241105licq_BSEP_DDA_60min/CAD20241105licq_BSEP_DDA_60min_m14-less3K_Slot2-8_1_3835_uncalibrated.mzML"
[23] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241120licq_BSEP_C8_PCP_DDA_60min/CAD20241120licq_BSEP_DDA_60min_m14_C8_Slot2-1_1_4073_uncalibrated.mzML"
[24] "/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241120licq_BSEP_C8_PCP_DDA_60min/CAD20241120licq_BSEP_DDA_60min_m14_PCP_Slot2-2_1_4074_uncalibrated.mzML"

In [42]:
# 修改了样本名匹配规则
get_ms2_count <- function(MZML_FILE){
    library("Spectra")
    ms <- Spectra(MZML_FILE)
    Sample <- str_extract(MZML_FILE, "(?<=min_).*?(?=_Slot)")
    ms2_count <- sum(msLevel(ms) == 2)
    df <- data.frame(Sample=Sample,ms2_count=ms2_count)
    return(df)
}

In [35]:
get_ms2_count("/rd1/user/lit/project/sORFs/raw_data/MS/Guomics_SP_MSdata/CAD20241120licq_BSEP_C8_PCP_DDA_60min/CAD20241120licq_BSEP_DDA_60min_m14_C8_Slot2-1_1_4073_uncalibrated.mzML")

  Sample ms2_count
1 m14_C8 112238

In [53]:
lapply(mzml,get_ms2_count) %>% do.call(rbind,.) -> sample_ms2_count

In [46]:
sample_ms2_count

   Sample     ms2_count
1  F1          38051
2  F2         176271
3  F3          65144
4  F4         174642
5  P1          49663
6  P2         175512
7  P3          68829
8  P4         175353
9  S1          71363
10 S2         172513
11 S3          57278
12 S4         170233
13 E16-N       32767
14 E16-N-T1   123461
15 E16-N-T2   124336
16 E16-T       36748
17 E16-T-LT   143663
18 E16-T-T    138098
19 E16-T-TC   130321
20 m14-10_30K 125809
21 m14-3_10K   91020
22 m14-less3K  40629
23 m14_C8     112238
24 m14_PCP    173839

In [55]:
sample_ms2_count$Sample <- gsub(pattern = "-",replacement = "_",x = sample_ms2_count$Sample)

In [56]:
sample_ms2_count

   Sample     ms2_count
1  F1          38051
2  F2         176271
3  F3          65144
4  F4         174642
5  P1          49663
6  P2         175512
7  P3          68829
8  P4         175353
9  S1          71363
10 S2         172513
11 S3          57278
12 S4         170233
13 E16_N       32767
14 E16_N_T1   123461
15 E16_N_T2   124336
16 E16_T       36748
17 E16_T_LT   143663
18 E16_T_T    138098
19 E16_T_TC   130321
20 m14_10_30K 125809
21 m14_3_10K   91020
22 m14_less3K  40629
23 m14_C8     112238
24 m14_PCP    173839

In [57]:
fwrite_c(sample_ms2_count,path = "./output/MS/stat/sample_ms2_count.txt")

# 20250505输入raw文件计算谱图数量

In [1]:
source("~/bin/lit_utils.R")
lib_text()

Warning message:
“程辑包‘stringr’是用R版本4.3.2 来建造的”

In [2]:
f <- "/rd1/user/lit/project/sORFs/raw_data/public_brain_MS/HLA/PXD019643/170509_AM_AUT01-DN04_Cerebellum_Tue39L243_10_DDA_1_400-1000mz_msms24_standard.raw"

In [4]:
library("Spectra")
ms <- Spectra(f)

ERROR: Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in substr(readBin(x, character(), n = 1), 1, 3): '<a1>F'多字节字符串有错

In [7]:
library(mzR)
raw <- openMSfile(f)  # 打开RAW文件
n_spectra <- length(header(raw)$seqNum)  # 获取谱图数量
print(n_spectra)

ERROR: Error in substr(readBin(x, character(), n = 1), 1, 3): '<a1>F'多字节字符串有错

In [8]:
f_1="/rd1/user/lit/project/sORFs/raw_data/public_brain_MS/non-HLA/PXD035950/adult_cortex_85872.raw"

In [9]:
library(mzR)
raw <- openMSfile(f_1)  # 打开RAW文件
n_spectra <- length(header(raw)$seqNum)  # 获取谱图数量
print(n_spectra)

ERROR: Error in substr(readBin(x, character(), n = 1), 1, 3): '<a1>F'多字节字符串有错